---

- name: Install Helm
  become: true
  shell: curl {{ helm_install_url }} | bash
  when: hostvars['variable_holder']['worker_node_status']  is success
  register: helm_install
  until: helm_install is success
  
# - name: Check if Prometheus is already installed
#   shell: kubectl get pods -A | grep prometheus | grep -c 'Running'
#   register: prometheus_check
#   changed_when: false

# - name: Install Prometheus using Helm
#   shell: helm install prometheus prometheus-community/prometheus --namespace monitoring --create-namespace
#   when: prometheus_check.stdout|int < 1
#   register: prometheus_install
#   until: prometheus_install is success

# - name: Confirm if Prometheus is running
#   shell: kubectl get pods -A | grep prometheus | grep -c 'Running'
#   when: prometheus_install is success
#   register: prometheus_status
#   until: prometheus_status.stdout|int >= 1
#   retries: 10
#   delay: 10
#   changed_when: false

# - name: Check if Grafana is already installed
#   shell: kubectl get pods -A | grep grafana | grep -c 'Running'
#   register: grafana_check
#   changed_when: false

# - name: Install Grafana using Helm
#   shell: helm install grafana grafana/grafana --namespace monitoring --create-namespace